CREATE TABLE task (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(20) NOT NULL,
    descricao VARCHAR(100), 
    prioridade VARCHAR(10) NOT NULL, 
    dataLimite DATE NOT NULL,
    concluida BOOLEAN NOT NULL,
    categoria VARCHAR(20) NOT NULL,
    criadaEm TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP 
);

